#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config focus_follows_pointer true

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################
xrdb -load ~/.Xresources &
dunst &
picom &
nitrogen --restore &
polybar -r bar1 &

# mpd 
xautolock -detectsleep -time 10 -locker "betterlockscreen -l dim" -notify 30 -notifier "notify-send -u critical -t 30 -- 'LOCKING screen in 30 seconds'" &
feh --bg-fill $HOME/Pictures/Wallpapers/catppuccin/waves.png
# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

bspc monitor HDMI-0 -d I III V VII IX
bspc monitor DP-2 -d II IV VI VIII X

bspc config border_width         1
bspc config window_gap           15

bspc config top_padding          37
bspc config bottom_padding       0

bspc config normal_border_color  "#18181B"
bspc config active_border_color  "#282828"
bspc config focused_border_color "#A0A0AB"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

bspc rule -a discord desktop=^1
bspc rule -a spotify desktop=^3
